---
services:
  soulmask:
    image: indifferentbroccoli/soulmask-server-docker
    platform: linux/amd64
    restart: unless-stopped
    container_name: soulmask
    stop_grace_period: 60s
    ports:
      - 8777:8777/udp
      - 27015:27015/udp
      - 18888:18888/tcp
    env_file:
      - .env
    volumes:
      - ./server-files:/home/steam/server-files
